development:
  adapter: mysql2
  encoding: utf8
  database: geo_tickets_development
  pool: 5
  username: root
  password:

production:
  adapter: mysql2
  encoding: utf8
  database: geo_tickets_production
  pool: 5
  username: root
  password:
